### ISSUE TITLE
Can make in CentOS

### ISSUE THREAD

**Issue by zouyx** [jrudolph/perf-map-agent#30]
Hi
   I have ran cmake .
   but show me as below
   do you know what it is happened?
   finished or unfinished?
```
   -- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:24 (include):
  include could not find load file:

    UseJava


CMake Error at CMakeLists.txt:30 (add_jar):
  Unknown CMake command "add_jar".


-- Configuring incomplete, errors occurred!
```

**Comment by jrudolph** [comment]
It means that your cmake installation is missing the `UseJava` module for some reason. In Ubuntu it is installed in `/usr/share/cmake-2.8/Modules/UseJava.cmake`.

**Comment by ceeaspb** [comment]
works for me on centos - please report the versions you are on?
Also the install/provisioning steps you ran to set up the environment.

**Comment by zouyx** [comment]
@jrudolph Thanks! I got it! 
@ceeaspb 
OS:CentOS release 6.3 (Final)
JDK:
java version "1.8.0_76-ea"
Java(TM) SE Runtime Environment (build 1.8.0_76-ea-b04)
Java HotSpot(TM) 64-Bit Server VM (build 25.76-b04, mixed mode)

My install step follow article which as blow
http://techblog.netflix.com/2015/07/java-in-flames.html
1.install perf: yum install perf
2.install cmake: yum install cmake
3.install jdk: download from http://openjdk.java.net
4.clone perf-map-agent from git ,compress it as tar , upload to server , run cmake . then cause a exception as my first post

**Comment by zouyx** [comment]
@jrudolph my cmake version is cmake version 2.6-patch 4
shall i update to 2.8?

**Comment by jrudolph** [comment]
Yes, probably. It [seems that](https://github.com/Kitware/CMake/commit/5c2106c71eb2a8b4e547b889fdc8aea3aeaad675) UseJava was added to cmake in 2.8.6.

**Comment by zouyx** [comment]
It works.........
after update cmake to 2.8.12.........

**Comment by jrudolph** [comment]
Cool, I added a comment in the README that cmake >= 2.8.6 is needed.
