### ISSUE TITLE
run perf script fail

### ISSUE THREAD

**Issue by zouyx** [jrudolph/perf-map-agent#31]
hello!    
i have a question about perf     
i ran the command as below    
```
perf script|./stackcollapse-perf.pl |./flamegraph.pl --color=java --hash > flamegraph1.svg
````   
system show me
```
Failed to open /usr/lib64/libc-2.17.so;56dd2155, continuing without symbols
Failed to open /usr/lib64/libpthread-2.17.so;56dd2155, continuing without symbols
```

os:CentOS Linux release 7.2.1511 (Core)
cmake:cmake version 2.8.11

**Comment by jrudolph** [comment]
Maybe you are missing debug symbols for libc and libpthread? In any case it shouldn't stop the process from run through. Did you get a `flamegraph1.svg`?

It doesn't seem directly related to perf-map-agent so I'm closing for now...

**Comment by zouyx** [comment]
i haven't got the svg...

**Comment by zouyx** [comment]
in fact........ i can get the svg...............
thanks jrudolph

**Comment by jazeltq** [comment]
how did you solve the problem? i met the same question...
