### ISSUE TITLE
incorrect method resolution?

### ISSUE THREAD

**Issue by phraktle** [jrudolph/perf-map-agent#4]
Hi,

I'm seeing some methods being unexpectedly listed high on perf top, which are called very infrequently. I have cross-checked with a JMC flight recording (which I assume to be quite accurate), and these paths were not showing up there at all.

Is there a chance that the map is somehow inaccurate, perhaps over time with hotspot recompiling / deoptimizing / moving stuff around?

Btw, this agent is quite useful, keep up the good work :)

Regards,
  Viktor

**Comment by jrudolph** [comment]
As @brendangregg noted above this should be fixed by now.
