### ISSUE TITLE
Perf not listing more than 1 line in JVM stack

### ISSUE THREAD

**Issue by rbalamohan** [jrudolph/perf-map-agent#70]
In one of my cluster, I can attach perf-map agent and get the symbol dump without issue.

I can record "perf record -F 99 -ag" and generate script via "perf script". However, it lists only one line for the JVM stack (the top frame in the stack). JVM is started with "-XX:-OmitStackTraceInFastThrow".

Has anyone observed something like this?

**Comment by apangin** [comment]
Perhaps you haven't set `-XX:+PreserveFramePointer`?
You may also try [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) - it does not require additional JVM options.

**Comment by rbalamohan** [comment]
I believe that is missed out for some reason. Added that and checking it. Thanks a lot. Yes, I use async-profiler regularly as well.

**Comment by rbalamohan** [comment]
BTW, I faced slightly different issue in async-profiler as well with these nodes. With async-profiler, it does not generate samples on these nodes and does not report errors as well. I have raised a ticket regarding this in async-profiler community.

**Comment by nitsanw** [comment]
Closing as per comment https://github.com/jvm-profiling-tools/perf-map-agent/issues/70#issuecomment-387551610 suggests the issue was misconfigured JVM
