### ISSUE TITLE
when do i have to create the map

### ISSUE THREAD

**Issue by cristifalcas** [jrudolph/perf-map-agent#82]
The perf map should be created before or after the per record/top commands?

**Comment by jrudolph** [comment]
You should first make sure that JIT is mostly done and the JVM is in a steady state and doesn't recompile things (e.g. using `-XX:+PrinCompilation`), then you can run the agent and afterwards the perf analysis tools. In general, it makes sense to run the map agent at a similar time as the collection to make sure the mapping is mostly correct. You can also see the provided scripts for some hints about things are usually done.

**Comment by cristifalcas** [comment]
Thank you
