### ISSUE TITLE
Running create-java-perf-map.sh in different containers in the same pod reports an error？

### ISSUE THREAD

**Issue by arrowfeng** [jrudolph/perf-map-agent#90]
Even though my pod uses the feature of shared pid, it still reports an error, what is the reason? Is there any solution?
![image](https://user-images.githubusercontent.com/20623365/162194507-73abc8a6-4171-4b9a-9aa4-a870c9c64231.png)

**Comment by jrudolph** [comment]
Attaching works by creating special files in special folders (I forgot which), so you will also have to share the right folders. You can look into `LinuxAttachProvider` to find how it works (which also has changed between JDK versions).

**Comment by arrowfeng** [comment]
Thank for your reply, it does create some files in the /tmp directory。
